[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
DATABASE_URL = "postgresql://postgres:justjuatjustjust@db.idyspefcwqpdnpvqrjtv.supabase.co:5432/postgres?sslmode=require"
